---
title: "Lab 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Read in dataset
```{r}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

Libraries
```{r}
library(dplyr)
library(stringr)
library(glue)
library(purrr)
library(english)
```


#Converts days in numerical form to the day spelled out
```{r}
xmas<-xmas%>%mutate(days_spelled=words(xmas$Day))
```

## Step One 
```{r}
pluralize_gift <- function(gift){

# gift <- gift %>%
#   str_replace("y$", "ies")
#   str_replace("[^y]$", glue("s"))
  
  gift<-str_replace(gift, "oo", "ee")
  gift<-glue("{gift}s")
  gift<-str_replace(gift, "ys$", "ies")



return(gift)



}

#pluralize_gift(xmas$Gift.Item)
```

## Step 2
```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location){
  
  
  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  sentence<-paste(num_word, adjective, item, verb, location)
  sentence<-str_trim(sentence)

  return(sentence)


}

# make_phrase(num = 10, 
#             num_word = "ten", 
#             item = "lords", 
#             verb = "a-leaping", 
#             adjective = "", 
#             location = "")

xmas<-xmas %>%
  mutate(
    Full.Phrase = pmap_chr(xmas,~make_phrase(..1, ..7, pluralize_gift(..3), ..4, ..5,..6))
  )
```


## Step 3
```{r}
sing_line <- function(dataset, line, phrase_col){

  phrases <- dataset %>% pull({{phrase_col}})
  # pmap_chr(xmas, ~make_phrase)
  for (i in line){
  return(glue("On the {line} day of Christmas, my true love sent to me, {phrases[i]} and {phrases[i-1]}"))
}

}

#sing_line(xmas, 3, Full.Phrase)
```


